---
title: How Americans’ Time-Use Patterns Changed over the Period 2003 - 2017
author: "Group July"
date: "26 November 2018"
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
output: pdf_document
indent: TRUE
fontsize: 11pt
urlcolor: blue
bibliography: Final-Report-References.bib
csl: ieee.csl
header-includes:
   - \usepackage{animate}
---

# Introduction

The aim of this report is to discover how Americans' time-use patterns have changed over the last 15 years or so. The datasets ([1](https://www.bls.gov/tus/special.requests/atussum_0317.zip) & [2](https://www.bls.gov/tus/special.requests/atusresp_0317.zip)) used to try and tackle this are results of the American Time Use Survey (ATUS) [@ATUS]. ATUS respondents are interviewed only one time about how they spent their time on the previous day, where they were, and whom they were with. The survey records the time spent on 431 different activities which are grouped into 17 different categories. In the analysis these categories will often be refered to by variable beginning with **tu** followed by a two-digit **category number**. The meaning of each category number can be found on the [ATUS website](https://www.bls.gov/tus/lexiconnoex0317.pdf).

The [Bureau of Labor Statistics website](https://www.bls.gov/tus/charts.htm) provides a number of simple charts, looking at the 2017 annual average for these categories. This report provides a more definitive conclusion on how time-use patterns changed over the period, evidenced with statistical investigation of the data. The findings explain in depth where some of the biggest fluctuations are and briefly note possible reasons for this. Limitations to the analysis are noted when appropriate and these must be taken into account when performing any further analysis or summaries; mentioned with any conclusions.   

# Exploratory Data Analysis

Fill in.

Talk about how we plotted for Train and Validate data for all of the models. Split data roughly in half to look at every other month, isolating our assigned month into the validation set. Then we will plot full models in next section.

# Dan's Stuff



# Gender Roles

A major news topic in recent years has been the division between genders in terms of roles and responsibilities. This debate has been fueled by a new wave of feminism, as well as a number of different campaigns, including *'#MeToo'* and *'Times Up'*. Both of these movements aim at addressing commonplace sexual harassment and discrimination and empowering women to take control. Given this backdrop, it was decided that an interesting area of the ATUS data to focus on would be the change in time use for different genders. Specifically, areas of time use where pre-existing gender roles are present were examined. 

Talcott Parsons' **[input BibTex reference here]** view of gender roles, developed in the 1950s, compared traditional gender roles with more liberal alternatives. A simplified version of the strictly traditional view of gender roles is detailed below. 

**Make this more formal**
```{r, echo=FALSE}
Male.Activities <- c("Working", "House Maintenance", "Vehicle Maintenance")
Female.Activities <- c("Housework", "Cooking", "Childcare")
kable(data.frame(Male.Activities, Female.Activities), col.names = c("Male Activites", "Female Activities"), align = rep('c', 2)) 
```

The liberal viewpoint discussed by Parsons suggests an equal balance of time for the genders in these roles. Whilst this study was developed over 50 years ago, a preliminary look at the data confirmed that, in 2003, a complete transition to the liberal viewpoint had not occurred. Therefore, it was decided to investigate whether the time use of these specific activities was heading to an equal split between the genders or whether it is stationary. Of course, it should be noted that 15 years is not a huge length of time to measure this sort of social change, as only a few sets of generations responses are recorded, however, it presents an interesting topic. 

For each of the 6 activities defined above, a general linear model or a linear model were produced and plotted below. 

For the generation classifications, we need to reference http://www.pewresearch.org/fact-tank/2018/03/01/millennials-overtake-baby-boomers/


Intro stuff, describe 
Chris and Harry doing in separate doc for now.

It was decided to model and plot male and female time spent independently as this is more intuitive and accessible to a reader than just the difference. Justification of not just plotting difference.

## Housework

Do the four

## Childcare

Do the four

## Food Preparation

Do the four

## Working Hours

Do the four

## House Maintenance

Quote a low participation rate, but could have potentially remained unchanged / more balanced to begin with?? Depends on if it is or not.

## Vehicle Maintenance

Similar to above, potentially unchanged or uninteresting.

# Limitations of the Data

15 years is a short period. Sporadic subset size due to the number of filters required to get down to the demographics we actually want to investigate. 

# References
